  version: '3.9'

  services:
    db:
      image: mysql
      # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
      # (this is just an example, not intended to be a production configuration)
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      env_file:
        - .env.db
      networks:
        - app
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        interval: 10s
        timeout: 10s
        retries: 3
      ports:
        - "3306:3306"
        - "33060:33060"

    adminer:
      image: adminer
      restart: always
      ports:
        - "3001:3001"
      networks:
        - app

    app:
      image: tawfiek/url-shortener
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app
      ports:
        - "3000:3000"
    web:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
      environment:
        - NGINX_PORT=80
      networks:
        - app
      depends_on:
        - app
  volumes:
    db:
  networks:
    app:

